# Generated by Django 4.0.6 on 2022-07-16 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_review_alter_actor_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='fees_in_world',
        ),
    ]
